### ISSUE TITLE
mosh terminates with “Socket not connected” after screen lock

### ISSUE THREAD

**Issue by smobbl-bobbl** [tbodt/ish#589] opened 2019-12-19 19:59 UTC
I connect to my AWS machine from iPad Pro via mosh. If I change to another app for too long or lock the screen, it is very likely that the top of the screen displays following message, including a count up:
`mosh:recvmsg: Socket not connected (1:06 without contact.) [To quit: Ctrl-^ .] `

and the terminal is dormant, no key input accepted. Also the quit sequence is not functional. When shut down iSH and reconnect, it detects a running mosh session (which means iSH could have reconnected to)

**Comment by tbodt** [comment] 2019-12-22 20:38
I haven't been able to reproduce this myself, but it sounds like one of the annoyances of https://developer.apple.com/library/archive/technotes/tn2277/_index.html.

**Comment by tbodt** [comment] 2019-12-22 21:03
I did just make it easier to press ctrl-^. It was possible, but you had to press ctrl-6 on a hardware keyboard. Now you can press ctrl-6 or ctrl-^ on the software keyboard as well.

**Comment by tbodt** [comment] 2020-01-01 23:19
Closing as "cannot reproduce"

**Closed by tbodt** 2020-01-01 23:19 UTC

**Comment by AndrewFarley** [comment] 2020-09-29 04:17
I just installed the latest beta on Test Flight and had both of these exact problems, which is possibly two separate issues, but also might be related idk.

OS: iOS 14.0.1
Device: iPad Pro (1st gen)

Problem #1: Why does a mosh session not allow to continue after being backgrounded for a while?

Problem #2: Why does the keyboard escape sequences no longer work at all.  Can't background it, can't quit it, etc.

Have been able to consistently replicate this bug
