### ISSUE TITLE
GDB bad system call

### ISSUE THREAD

**Issue by ForceBru** [tbodt/ish#396] opened 2019-05-28 07:21 UTC
I'm trying to debug some simple code (the code itself works, I just wanted to test if gdb works), but gdb reports a bad syscall:

```
iPhone-ForceBru:~# cat test.c                               
#include <stdio.h>                                     
                                                       
int main(void) {                                       
        int a = 5, b = 7;                              
        printf("The result is: %d\n", (a+b)*3);        
        return 0;                                      
}                                                      
iPhone-ForceBru:~# clang test.c                             
iPhone-ForceBru:~# gdb a.out                                
GNU gdb (GDB) 8.2                                      
Copyright (C) 2018 Free Software Foundation, Inc.      
# ...snip...
This GDB was configured as "i586-alpine-linux-musl".   
# ...snip...            
Reading symbols from a.out...done.      
(gdb) r                                                
Starting program: /root/a.out                          
Bad system call                                        
iPhone-ForceBru:~# dmesg                                    
unknown ioctl 5600                                     
unknown ioctl 5429                                     
unknown ioctl 5409                                     
unknown ioctl 5422                                     
unknown ioctl 5422                                     
unknown ioctl 5429                                     
unknown ioctl 5409                                     
unknown ioctl 5422                                     
unknown ioctl 5422                                     
unknown ioctl 5429                                     
unknown ioctl 5409                                     
unknown ioctl 5429                                     
unknown ioctl 5409                                     
unknown ioctl 5429                                     
unknown ioctl 5409                                     
unknown ioctl 5422                                     
unknown ioctl 5429                                     
unknown ioctl 5409                                     
unknown ioctl 5413                                     
unknown ioctl 5413                                     
19 missing syscall 136
```

Opcode 136 is `sys_personality`: https://github.com/torvalds/linux/blob/cd6c84d8f0cdc911df435bb075ba22ce3c605b07/arch/x86/entry/syscalls/syscall_32.tbl#L150

**Comment by saagarjha** [comment] 2019-05-28 07:25
136 is `sys_personality`: as far as I can tell it's not very important since you can get pretty far even with it stubbed out. After that, though, you're going to be missing `sys_ptrace` which is complicated: see #47.

**Comment by tbodt** [comment] 2019-05-28 07:26
Closing as duplicate of #47

**Comment by tbodt** [comment] 2019-05-28 07:26
personality is probably being used to disable ASLR which ish doesn't have anyway.

**Comment by ForceBru** [comment] 2019-05-28 07:27
So, is it not possible to debug programs yet?

**Closed by tbodt** 2019-05-28 07:26 UTC

**Comment by tbodt** [comment] 2019-05-28 07:27
Not yet

**Comment by saagarjha** [comment] 2019-05-28 07:28
> personality is probably being used to disable ASLR which ish doesn't have anyway.

Yup, I've stubbed it out with this:

```c
dword_t syscall_success_stub() {
    return 0;
}
```

**Comment by ForceBru** [comment] 2019-05-28 07:29
@tbodt, that's a pity. Still this is one _great_ app, good job!

**Comment by saagarjha** [comment] 2019-05-28 07:31
Little known fact: @tbodt is actually an advanced neural network hooked up to GitHub between 8 AM and 1 AM

**Comment by MatthewMerrill** [comment] 2019-05-28 07:32
Arizona goes in one end, code comes out the other. It's a tea bot.
