### ISSUE TITLE
tmux crashes the terminal.

### ISSUE THREAD

**Issue by Ladizii** [tbodt/ish#134] opened 2018-11-27 23:52 UTC
Termux crashes the app when you run it, but you're able to install it properly and everything like normally.

**Comment by tbodt** [comment] 2018-11-28 00:51
tmux is going to be hard to get working because it requires pseudoterminals. But it should give a "bad system call", not crash the app. Termux is unrelated to tmux, title updated.

**Comment by Ladizii** [comment] 2018-11-28 00:53
I confused it for a second, anyways it does crash the app.

**Comment by tbodt** [comment] 2018-12-02 05:30
Gonna close this as duplicate of #46

**Closed by tbodt** 2018-12-02 05:30 UTC
