### ISSUE TITLE
Error when using nmap.

### ISSUE THREAD

**Issue by Gamerexde** [tbodt/ish#643] opened 2020-02-18 15:24 UTC
Error when using Nmap.

`Phone-de-XD-:~# nmap 192.168.0.1
Starting Nmap 7.70 ( https://nmap.org ) at 2020-02-18 15:21 UTC
route_dst_netlink: cannot create AF_NETLINK socket: Invalid argument `

**Comment by tbodt** [comment] 2020-02-18 17:41
Duplicate of #166

**Closed by tbodt** 2020-02-18 17:41 UTC
