### ISSUE TITLE
MTR works sometimes

### ISSUE THREAD

**Issue by intdel** [tbodt/ish#657] opened 2020-03-19 21:20 UTC
mtr only seems to work sometimes.

The-iPad:~# mtr 8.8.8.8
mtr: Packet type unsupported: Invalid argument

If I keep calling mtr it will work after some time. So it is really random.

This is on an iPad 11 Pro with iOS 13.4

**Comment by tbodt** [comment] 2020-03-19 21:41
Duplicate of #364

**Closed by tbodt** 2020-03-19 21:41 UTC
