### ISSUE TITLE
Git pull fails

### ISSUE THREAD

**Issue by moldabekov** [tbodt/ish#636] opened 2020-02-10 12:08 UTC
_Hello,_

_first of all let me thank you for such fantastic tool you brought to us! I do enjoy using it, it covers me a lot in my daily routine!_

I didn’t find any exact issues related to this issue. The most closest one is https://github.com/tbodt/ish/issues/373.

I use zsh as my primary shell with [Oh my zsh](https://ohmyz.sh/). Vendor provides with the upgrade scripts which basically pulls any new commits and rebases it.

When you call `upgrade_my_zsh` it fails with `error: inflate: data stream error (incorrect header check`.

Device: iPad Pro 11
iPad OS: 13.3.1
iSH: 1.0 (64)
ZSH: 5.6.2
GIT: 2.20.2

![6FC6DA5D-DA4F-4519-8FD9-C36F9E6F96C1](https://user-images.githubusercontent.com/669547/74148740-5667b600-4c30-11ea-848b-af922efbc7e8.png)

**Comment by tbodt** [comment] 2020-02-10 15:46
Duplicate of #373

**Closed by tbodt** 2020-02-10 15:46 UTC
