### ISSUE TITLE
java vm crashes when trying to run a minecraft server

### ISSUE THREAD

**Issue by VincentCCandela** [tbodt/ish#592] opened 2019-12-23 21:57 UTC
Error:

Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap

Steps to Reproduce:

1. Install java8 with "apk add openjdk8"
2. Add a user for minecraft "adduser minecraft"
3. Download the server jar "wget https://launcher.mojang.com/v1/objects/3737db93722a9e39eeada7c27e7aca28b144ffa7/server.jar -O minecraft_server.1.13.jar"
4. Create a script to run the jar:

![IMG_4352](https://user-images.githubusercontent.com/31104403/71382251-14fa4900-25a5-11ea-9503-064840f4f1a5.jpeg)

5. Mark the script as executable "chmod +x run.sh"
6. Run the script ./run

**Comment by ntindle** [comment] 2019-12-25 17:59
Try the script without Xms and Xmx

**Comment by VincentCCandela** [comment] 2019-12-27 00:40
If I do that then I get this error:


```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0xe81c301d, pid=18, tid=0xf7181d88
#
# JRE version: OpenJDK Runtime Environment (8.0_222-b10) (build 1.8.0_222-b10)
# Java VM: OpenJDK Server VM (25.222-b10 mixed mode linux-x86 )
# Derivative: IcedTea 3.13.0
# Distribution: Custom build (Wed Oct  2 14:20:26 UTC 2019)
# Problematic frame:
# J 136 C1 java.util.zip.ZipCoder.getBytes(Ljava/lang/String;)[B (192 bytes) @ 0xe81c301d [0xe81c1ce0+0x133d]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /root/hs_err_pid18.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla
```

When I enable core dumps, I get this error: 

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0xe81cf69d, pid=29, tid=0xf7181d88
#
# JRE version: OpenJDK Runtime Environment (8.0_222-b10) (build 1.8.0_222-b10)
# Java VM: OpenJDK Server VM (25.222-b10 mixed mode linux-x86 )
# Derivative: IcedTea 3.13.0
# Distribution: Custom build (Wed Oct  2 14:20:26 UTC 2019)
# Problematic frame:
# J 172 C1 java.util.zip.ZipCoder.getBytes(Ljava/lang/String;)[B (192 bytes) @ 0xe81cf69d [0xe81ce360+0x133d]
#
# Core dump written. Default location: /root/core or core.29
#
# An error report file with more information is saved as:
# /root/hs_err_pid29.log
```

I've attached the two error reports:

[hs_err_pid18.log](https://github.com/tbodt/ish/files/4003715/hs_err_pid18.log)
[hs_err_pid29.log](https://github.com/tbodt/ish/files/4003718/hs_err_pid29.log)

**Comment by tbodt** [comment] 2019-12-27 00:52
Think this is fincstp

**Comment by tbodt** [comment] 2020-01-01 23:20
This is really a dupe of #306

**Closed by tbodt** 2020-01-01 23:20 UTC

**Comment by lianglingbo** [comment] 2021-01-08 06:42
I find the way to solution the jvm cant run problem.
you should add this config when you are  install openjdk
my config like this :
  iPad:~# cat /etc/profile
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PAGER=less
export PS1='\h:\w\$ '
umask 022

for script in /etc/profile.d/*.sh ; do
        if [ -r $script ] ; then
                . $script
        fi
done
export JAVA_TOOL_OPTIONS="-Xmx16m -Xms1m -Dfile.encoding=UTF-8"
export JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
export PATH=$JAVA_HOME/bin:$PATH
export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/jre/lib/rt.jar
iPad:~# java -version
Picked up JAVA_TOOL_OPTIONS: -Xmx16m -Xms1m -Dfile.encoding=UTF-8
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (IcedTea 3.16.0) (Alpine 8.252.09-r0)
OpenJDK Server VM (build 25.252-b09, mixed mode)
