### ISSUE TITLE
dig causes crash

### ISSUE THREAD

**Issue by singe** [tbodt/ish#290] opened 2019-01-28 10:45 UTC
Running dig without switches leads to a repeatable app crash. Even after a fresh install. Can’t get dmesg output. Crash dump follows. 

Date/Time:           2019-01-28 12:16:13.2198 +0200
Launch Time:         2019-01-28 12:15:50.3562 +0200
OS Version:          iPhone OS 12.1.2 (16C101)
Baseband Version:    1.02.18
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Subtype: KERN_PROTECTION_FAILURE at 0x000000016d694000
VM Region Info: 0x16d694000 is in 0x16d694000-0x16d698000;  bytes after start: 0  bytes before end: 16383
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      Stack                  000000016d60c000-000000016d694000 [  544K] rw-/rwx SM=COW  thread 9
--->  STACK GUARD            000000016d694000-000000016d698000 [   16K] ---/rwx SM=NUL  ... for thread 5
      Stack                  000000016d698000-000000016d720000 [  544K] rw-/rwx SM=COW  thread 5

Termination Signal: Bus error: 10
Termination Reason: Namespace SIGNAL, Code 0xa
Terminating Process: exc handler [13256]
Triggered by Thread:  9

Thread 9 Crashed:
0   iSH                           	0x0000000102b4f738 0x102b40000 + 63288
1   iSH                           	0x0000000102b60c00 0x102b40000 + 134144
2   iSH                           	0x0000000102b60dac 0x102b40000 + 134572
3   iSH                           	0x0000000102b4f2d8 0x102b40000 + 62168
4   iSH                           	0x0000000102b689b0 0x102b40000 + 166320
5   iSH                           	0x0000000102b4fd6c 0x102b40000 + 64876
6   libsystem_pthread.dylib       	0x00000001aae87974 0x1aae86000 + 6516
7   libsystem_pthread.dylib       	0x00000001aae878d0 0x1aae86000 + 6352
8   libsystem_pthread.dylib       	0x00000001aae8fddc 0x1aae86000 + 40412

**Comment by tbodt** [comment] 2019-01-28 16:07
Duplicate of #141. The dmesg crash is fixed.

**Closed by tbodt** 2019-01-28 16:07 UTC
