### ISSUE TITLE
screenfetch not working: awk and grep fighting

### ISSUE THREAD

**Issue by jusdepatate** [tbodt/ish#146] opened 2018-12-01 13:42 UTC
Hi, Another Issue:tm: today, about screenfetch this time.
When I curl the url of screenfetch, I get a battle between awk and grep because /proc/cpuinfo does not exist, full log:
```
iPad~# curl -s https://raw.githubusercontent.com/KittyKatt/screenFetch/master/screenfetch-dev | bash                                                                                                
awk: /proc/cpuinfo: No such file or directory                                                                                              
grep: /proc/cpuinfo: No such file or directory                                                                                             
awk: /proc/cpuinfo: No such file or directory                                                                                              
awk: /proc/cpuinfo: No such file or directory                                                                                              
grep: /proc/cpuinfo: No such file or directory                                                                                             
awk: /proc/cpuinfo: No such file or directory    
```
And then nothing...

**Comment by tbodt** [comment] 2018-12-01 17:01
I'm gonna call this a duplicate of #148

**Closed by tbodt** 2018-12-01 17:01 UTC

**Comment by jusdepatate** [comment] 2018-12-01 17:03
Oh sorry, didn't see
