### ISSUE TITLE
The motd references a command that doesn’t exist

### ISSUE THREAD

**Issue by eric** [tbodt/ish#115] opened 2018-11-18 21:46 UTC
I noticed this in the motd but couldn’t find the command:
                                                 
```
You can setup the system with the command: setup-
alpine
```

**Comment by saagarjha** [comment] 2018-11-18 21:48
This has been fixed in master via ad33d1029c0f2ff48b7df104e95233f44737810e. It should be in the next TestFlight build.

**Comment by tbodt** [comment] 2018-11-18 21:48
Duplicate of #78

**Closed by tbodt** 2018-11-18 21:48 UTC
