### ISSUE TITLE
ssh-keygen is very slow

### ISSUE THREAD

**Issue by Jon-Schneider** [tbodt/ish#41] opened 2018-11-11 18:37 UTC
Ssh-keygen hangs on "Generating public/private rsa key pair".

**Comment by tristan-k** [comment] 2018-11-14 11:43
I just did the same without any issues.

**Comment by Jon-Schneider** [comment] 2018-11-14 16:56
I decided to wait for a while and see what happened. 2048 keys take 2-3 minutes, and 4096 bit keys take 5-6 minutes (vs. instantaneous on Mac). So it does eventually work but the amount of time it takes might be a side effect of the emulation.

**Comment by tbodt** [comment] 2018-11-15 03:51
Yeah, things tend to be pretty slow. Fixing that isn't as high priority as making things work at all, of course.

**Comment by tbodt** [comment] 2018-11-28 04:40
Closing as duplicate of #129.

**Closed by tbodt** 2018-11-28 04:40 UTC

**Comment by KritantaDev** [comment] 2020-12-10 17:55
This issue can be negated by using `ssh-keygen -b 1024` which takes about 1.5s to run.

Note this weakens security slightly, although the risk here is very debatable.
