### ISSUE TITLE
rustup fails to install

### ISSUE THREAD

**Issue by AndrewSB** [tbodt/ish#474] opened 2019-09-02 15:17 UTC
`curl https://sh.rustup.rs -sSf | sh` results in

```
info: downloading installer                                                                                                        
sh: /tmp/tmp.S88nsFMATQ/rustup-init: not found
```

somewhat related to #67, but it seems to be a different problem

**Comment by tbodt** [comment] 2019-09-02 15:18
Duplicate of #355

**Closed by tbodt** 2019-09-02 15:18 UTC
