### ISSUE TITLE
Can't install exercism

### ISSUE THREAD

**Issue by hellosze** [tbodt/ish#500] opened 2019-10-02 17:31 UTC
I can't install exercism.  
I used the linux 32bit release of exercism
https://github.com/exercism/cli/releases

Error is:
`This program can only be run on processors with MMX support.`

**Comment by Mnpn03** [comment] 2019-10-02 17:33
iSH doesn't have MMX instructions yet. Similar to #57

**Comment by tbodt** [comment] 2019-10-02 20:32
Duplicate of #57

**Closed by tbodt** 2019-10-02 20:32 UTC
