### ISSUE TITLE
Perl 5 doesn’t work

### ISSUE THREAD

**Issue by SteveMarshall** [tbodt/ish#191] opened 2018-12-15 09:27 UTC
From a completely vanilla, new install of iSH:

```
Steves-iPhone:~# apk add perl                    
(1/1) Installing perl (5.26.3-r0)                
Executing busybox-1.28.4-r0.trigger              
OK: 97 MiB in 25 packages                        
Steves-iPhone:~# perl                            
Illegal instruction                              
Steves-iPhone:~#                                 
```

**Comment by ELChris414** [comment] 2018-12-15 09:51
dmesg gives: 5 illegal instruction at 0xf7e3d198: df 5c 24 2a d9 6c
 24 2e

**Comment by tbodt** [comment] 2018-12-15 15:55
This is a duplicate of #179 which is fixed in master.

**Closed by tbodt** 2018-12-15 15:55 UTC
