### ISSUE TITLE
lsyncd fails

### ISSUE THREAD

**Issue by drpump** [tbodt/ish#318] opened 2019-02-19 01:15 UTC
I get a bad system call trying to run lsyncd. dmesg: 

```
iPad:~# lsyncd -rsync synctest me@192.168.1.1:tmp                                                                                                                       
Bad system call                                                                                                                                                             
iPad:~# dmesg | tail -10                                                                                                                                                    
unknown ioctl 5413                                                                                                                                                          
unknown ioctl 5413                                                                                                                                                          
resizing to 0                                                                                                                                                               
resizing to 1877257320                                                                                                                                                      
resizing to 1877290672                                                                                                                                                      
172 missing syscall 332                                                                                                                                                     
resizing to 0                                                                                                                                                               
resizing to 0                                                                                                                                                               
resizing to 1877257320                                                                                                                                                      
resizing to 1878977640                                                                                                                                                      
```

**Comment by tbodt** [comment] 2019-02-19 01:15
332 is inotify_init1

**Comment by drpump** [comment] 2019-02-19 01:17
Note that I’m looking for a way to automatically update a remote server with local changes (coding locally, running in cloud). `rsync` works but is manual. Great work on iSH so far, by the way.

**Comment by tbodt** [comment] 2019-02-19 01:18
Any program that syncs automatically would probably report exactly the same missing syscall, since that's the one you need to get notified when files change.

**Comment by tbodt** [comment] 2019-02-19 01:20
Had an idea: write a script that runs rsync every 10 seconds.

**Comment by drpump** [comment] 2019-02-19 01:25
Yes, quite do-able. Just thought I’d try lsyncd to see if it worked :).

**Comment by tbodt** [comment] 2019-09-22 08:33
Marking as duplicate of #491

**Closed by tbodt** 2019-09-22 08:33 UTC
