### ISSUE TITLE
Crash when running yarn

### ISSUE THREAD

**Issue by whtsky** [tbodt/ish#333] opened 2019-03-06 18:41 UTC
I upgraded to alpine 3.9 repository:
```bash
# cat /etc/apk/repositories                                                                                               
http://dl-cdn.alpinelinux.org/alpine/v3.9/main                                                                                             
http://dl-cdn.alpinelinux.org/alpine/v3.9/community
```

[iSH-2019-03-07-023252.ips.zip](https://github.com/tbodt/ish/files/2937795/iSH-2019-03-07-023252.ips.zip)

**Comment by tbodt** [comment] 2019-03-10 07:50
I can't reproduce this from a clean install.

**Comment by whtsky** [comment] 2019-03-10 08:28
I clean installed iSH 1.0(48) then got the Illegal instruction error.
![A1AEE9DA-C1C3-4DA4-8A51-091BFC9EAD86](https://user-images.githubusercontent.com/876694/54082459-37421380-4351-11e9-8d0a-77757d428b28.png)

dmesg output:
[dmesg.txt](https://github.com/tbodt/ish/files/2949222/dmesg.txt)

**Comment by tbodt** [comment] 2019-03-10 17:58
Illegal instruction is duplicate of #90. Crash shouldn't be happening...

**Closed by tbodt** 2019-03-10 17:58 UTC
