### ISSUE TITLE
git-lfs need MMX support

### ISSUE THREAD

**Issue by roxtigger2003** [tbodt/ish#579] opened 2019-12-09 04:49 UTC
![7CFF1E6A-0A50-4940-A170-08A25FF8AD81](https://user-images.githubusercontent.com/36947924/70408217-ea26d580-1a79-11ea-96a5-fd15c97203d2.jpeg)

**Comment by tbodt** [comment] 2019-12-09 04:54
Duplicate of #57

**Closed by tbodt** 2019-12-09 04:54 UTC
