### ISSUE TITLE
Feature request: add “|”, “<“ and “>” to the extra keyboard row

### ISSUE THREAD

**Issue by fernandotcl** [tbodt/ish#74] opened 2018-11-13 07:01 UTC
I believe that adding the pipe and greater than / lesser than keys would be useful since they’re very frequently used when operating the shell.

There might not be enough room on the iPhone, but there should be enough room on the iPad.

**Comment by bvandergiessen** [comment] 2018-11-14 11:39
Also, arrow buttons (instead of/in addition to the four-arrow drag button) would be useful, especially when editing a command, where you have to hit the forward and backward arrows multiple times in a row.

**Comment by tbodt** [comment] 2018-11-15 03:50
You can drag the arrow button to the side and hold your finger there to repeatedly press an arrow.

**Comment by tbodt** [comment] 2019-07-21 02:08
Closing as duplicate of #311

**Closed by tbodt** 2019-07-21 02:08 UTC
