### ISSUE TITLE
Python run too slow

### ISSUE THREAD

**Issue by Zxilly** [tbodt/ish#331] opened 2019-03-03 07:06 UTC
It run too slow that I even doubt it is broken.
I run ish on iPad mini 2 with iOS 12.1.4.
`pip -V`spend me 7 minutes to wait for the response.
Any performance improve suggestion?
I use `apk add python3` to install python3

**Comment by tbodt** [comment] 2019-03-03 07:07
There's really nothing I can do about it. It runs somewhat faster than that for me on an iPad Pro 10.5", because the processor is faster. Closing as duplicate of #129

**Closed by tbodt** 2019-03-03 07:07 UTC

**Comment by Phearith1989** [comment] 2020-03-25 21:55
I am new how to use ish after install python?

**Comment by Zxilly** [comment] 2020-03-29 10:04
> I am new how to use ish after install python?

@Phearith1989 use the pkg manager to install python and just use it
