### ISSUE TITLE
wget issue

### ISSUE THREAD

**Issue by francoisvignon** [tbodt/ish#216] opened 2018-12-23 12:54 UTC
a random bad bug (at least with commit fd48ae6, f802873, maybe also with c846847, will try with old commit when I have some time)

sometime wget issue with "wget: read error: Invalid argument"
and the same url with curl work fine.
seem to be related to network.

you can try with following url:
https://dl.i4th.me/a, this one should retrieve a 41KB file
https://dl.i4th.me/b, this one should retrieve a 5KB file
sometime only wget for b work, sometime both work, sometime none work
no failure at this time with curl

**Comment by tbodt** [comment] 2018-12-23 19:01
I can’t reproduce this.

**Comment by Mnpn03** [comment] 2018-12-23 19:12
Can’t reproduce.

**Comment by ELChris414** [comment] 2018-12-23 19:15
Can't reproduce.

**Comment by tbodt** [comment] 2018-12-23 19:38
It is likely a bug in iSH, I just don't have any way to debug it since I don't have any way to make it happen again.

**Comment by francoisvignon** [comment] 2018-12-23 20:07
Yes, I understand.
as the problem don’t occurs with the officlal testflight beta 37, I will try do compile again the beta 37.

thanks for your patience.

**Comment by francoisvignon** [comment] 2018-12-24 08:43
I have rebuild with commit tagged builds/beta/37:
wget works fine :-)

it’s mean two things: 
1) my build process is not wrong :-)
2) the wget issue was in a commit after beta/37 :-/

so, if you want, I can check several commit before the beta/37 and the last one from this sunday … but if you prefer, I can wait for next official beta.
I know testing things not done to be tested can be annoying.

Kind regards

**Comment by francoisvignon** [comment] 2018-12-24 09:11
After some try, the wget issue come with commit 
D8ca7249c739dbebb75a85da86e5b35e4af74892, debuger show SIGPIPE
the commit just before (2297838700f904cb7f7df9dca8c2596ed2adfea2) don't broke wget

the "faulty" commit address just O_APPEND flag

**Comment by francoisvignon** [comment] 2018-12-24 17:31
wget fail with this URL : https://dl.i4th.me/a but not with https://dl.i4th.me/b and work with some other one. very strange.

can you tell me where I can find sources of wget to investigate a little bit what can be the error ?

**Comment by francoisvignon** [comment] 2018-12-24 17:45
when commenting lines in real.c:
// if (flags & O_NONBLOCK_) real_flags |= O_NONBLOCK;
and
// if (flags & O_NONBLOCK) fake_flags |= O_NONBLOCK_;

wget don't fail anymore, no longer SIGPIPE.

**Comment by tbodt** [comment] 2018-12-24 18:07
Thanks for bisecting! The source for the built-in wget is here: https://github.com/mirror/busybox/blob/master/networking/wget.c

You can enable logging of every system call in Xcode by going to build settings for the project, scrolling down, and changing the ISH_LOG setting to strace.

**Comment by francoisvignon** [comment] 2018-12-27 18:33
Hi

still investigating wget failure …. 
problem seem to be at file stream level (I don’t like file stream, I prefer using raw file operation)

find nothing (at this time) from your side :-/
 


_____________
Francois

**Comment by francoisvignon** [comment] 2018-12-28 09:46
I think I see the issue:
it seem busybox was not compiled with same errno definition than yours and so, EAGAIN as not same value for busybox and for you:

errno 11 for you is EAGAIN
errno 35 for Mac is EAGAIN 
ok, you make the correct translation in open_flags_real_from_fake and reverse

but for busybox errno 11 is "invalid argument", not "Try Again" or "Resource temporarily unavailable" (for Mac, errno 11 is Resource deadlock avoided).


please find bellow all errno code I have identified for busybox, very few match GNU or Mac:
-1
No such file or directory
-2
Interrupted system call
-3
No such device or address
-4
Exec format error
-5
No child process
-6
Out of memory
-7
Bad address
-8
Resource busy
-9
Cross-device link
-10
Not a directory
-11
Invalid argument
-12
No file desc. Av.
-13
Text file busy
-14
No space left on device
-15
Read only file system
-16
Broken pipe
-17
Result not representable
-18
File name too long
-19
Function not implementend
-20
Symbolic link loop
-21
No message of desired type
-30
Device not a stream
-31
Device timeout
-37
Bad message
-42
Illegal byte sequence
-44
Not a socket
-45
Message too large
-46
Protocole not available
-47
Socket type not supported
-48
Protocole family not supported
-49
Address in use
-50
Network is down



____________________

Francois

**Comment by francoisvignon** [comment] 2018-12-28 17:31
I think I’m right … the value of EAGAIN used to compile busybox should not be the same that one GNU and you use.

this one explain the message "wget: read error: Invalid argument", according my previous email, "Invalid argument" is the error message corresponding to errno 11as show by busybox.
and according wget.c source:
...
if (errno != EAGAIN) {
    if (ferror(dfp)) {
       progress_meter(PROGRESS_END);
         bb_perror_msg_and_die(bb_msg_read_error);
    }
    break; /* EOF, not error */
}
…

read error message are issued only if errno != EAGAIN and syscall tracing show you set well errno to EAGAIN (11).
so, errno is != EAGAIN, because we have the message and the displayed message correspond to errno = 11, consequently, EGAIN != 11

I have asked alpine about the EAGAIN value used to compile busybox :-)

please note, this problem is not here when installing wget with "apk add wget", but this one don’t do the same thing than the built-in (it don’t use O_NONBLOCK).

So, I think this problem will probably occurs with different busybox tools in case of error managed at errno level.
maybe you should setup a busybox version compiled from gnu tools ?

A side effect of that is you don’t have issue related to O_ NONBLOCK :-)

I wish you an Happy New Year

_____________
Francois

**Comment by tbodt** [comment] 2018-12-28 18:20
The correct Linux value of EAGAIN is 11 apparently: https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/errno-base.h

Where did you find that 11 is invalid argument for busybox? It should be using the error number info in the C library.

**Comment by francoisvignon** [comment] 2018-12-28 19:37
in wget.c, the message related to errno is displayed using strerror(), so I cheat the exit code of sys_read to issue various error (and so errno) making busybox’s wget displaying his errno meaning (I do for errno from 1 to 40, it’s the table I send you).

as send previously, wget issue read error (with errno’s explanation) if it’s a read failure (like one occuring with non blocking and no data).

if the errno is not EAGAIN, the error message is displayed (read error: + translation of errno).
as the errno is set to 11 and sys_read exit with -11, read in wget fail and issue the error message : this should not happen, because errno is set to EAGAIN (11) and the errno is only displayed if errno != EAGAIN, meaning the compiled value of EGAIN in busybox is not 11. for busybox’s compilation, 11 is "invalid argument" (EINVAL, errno 22 in GNU), not EAGAIN.

please note errno value are not standard: as example, iOs/OSx/BSD, EAGAIN is 35, in GNU based is 11

if you look the table, it’s very few common errno between one used and interpreted by busybox, one defined by GNU and defined in OSx/iOs/BSD.

so, if you compile busybox in iSH environment (GNU), wget.c will be compiled with EAGAIN defined as 11 and wget will work fine.
unfortunately, I don’t find any information on alpine site about the compilation environment used to generate busybox for x86, so I ask them.


in all case, if errno is set to 11 by your sys_read, wget use it and the only way to have the error message mean errno set to 11 is different from EGAIN (defined during busybox compilation).



_____________
Francois

errno table for busybox (the one from alpine tar):
-1	No such file or directory
-2	Interrupted system call
-3	No such device or address
-4	Exec format error
-5	No child process
-6	Out of memory
-7	Bad address
-8	Resource busy
-9	Cross-device link
-10	Not a directory
-11	Invalid argument
-12	No file desc. Av.
-13	Text file busy
-14	No space left on device
-15	Read only file system
-16	Broken pipe
-17	Result not representable
-18	File name too long
-19	Function not implementend
-20	Symbolic link loop
-21	No message of desired type
-30	Device not a stream
-31	Device timeout
-37	Bad message
-42	Illegal byte sequence
-44	Not a socket
-45	Message too large
-46	Protocole not available
-47	Socket type not supported
-48	Protocole family not supported
-49	Address in use
-50	Network is down

**Comment by francoisvignon** [comment] 2018-12-29 17:33
no, in fact, it’s various, not directly related to https or http:
in example for me http://dl.i4th.me/a or https://dl.i4th.me/a issue always an error.

no news from alpine at this time about there errno value definition ;-)

using your test/get-busybox.sh, I have try to compile with gcc in iSH but I got an error during make defconfig (internal error, not a directory, or something like that).

I think if you setup a busybox using correct tools and put in iSH, the problem will be solved.
I have not enough time to setup a correct environment to compile busybox at this time, but if you can and you send to me the busybox exec, I can use it.

**Comment by francoisvignon** [comment] 2019-01-05 15:19
Problem identified and Issue solved !!! 

wget make use of sys_readv calling  sys_read calling realfs_read 

When EGAIN error occurs in realfs_read:
- realfs_read return -11
- In sys_read res (definied as int_t) is set to -11
- sys_read is defined as dword_t
- and the value used to setup res (defined as dword_t) in sys_readv is 4294967285 (not -11)
	 
And so, the subsequent test (res < 0) is not true and the error is not propagated.
	
**Defining res as int_t in fs.c/sys_readv (as in fs.c/sys_read) solve the wget issue** 
NB: wget and all other using readv with read issuing an error

I think it's the also an issue in sys_writev (res is also defined as dword_t) and maybe in another function ...

and so, the uncorrect conversion of res as big integer explain my misunderpretation of errno labeling (please forget it).

in all case, I can reproduce the bug/correction by setting res as dword_t/int_t.
will do some test to find where the conversion between (int_t) -11 into double_t result in 4294967285 and not in -11.

**Comment by tbodt** [comment] 2019-01-05 17:21
thanks so much for debugging!! why the hell didn’t the compiler warn me that that comparison would always be false...

**Comment by francoisvignon** [comment] 2019-01-05 17:33
I think the problem is not in the test but in type conversion by the compiler.

So, I think this issue (wget) can be closed once you have checked my proposal :-)

don't worry, more issue to come ... ;-)

**Comment by tbodt** [comment] 2019-01-06 02:11
The latest commit should include a fix for this. Let me know if it doesn't work.

**Closed by tbodt** 2019-01-06 02:11 UTC
Labels: no repro

**Comment by francoisvignon** [comment] 2019-01-06 10:14
it's work ... but (still a but), you have modified a lot of file ... lot of things to test again ;-)
