### ISSUE TITLE
Function keys

### ISSUE THREAD

**Issue by Daisuke-sama** [tbodt/ish#547] opened 2019-10-29 11:50 UTC
Hi,
Cool app, 
I have been stumbled by F keys using the Smart Keyboard. Are there any way to reach that stuff?

**Comment by tbodt** [comment] 2019-11-03 00:25
No. Why do you need them? FYI Midnight Commander lets you use esc+1 instead of f1.

Duplicate of #311

**Closed by tbodt** 2019-11-03 00:25 UTC

**Comment by 7heaven** [comment] 2023-02-23 05:18
same problem here, I login to my router via ssh using ish, my router runs RouterOS and F1 act as help command and it didn't work
