### ISSUE TITLE
iSH will become unable to be launched after running fish

### ISSUE THREAD

**Issue by kkk669** [tbodt/ish#121] opened 2018-11-21 17:04 UTC
Steps to reproduce:

1. (Optional) Run `apk update`
2. Run `apk add fish`
3. Run `fish` (Then, iSH doesn’t respond even if I press keys such as Ctrl+C.)
4. Show the application switcher and swipe up iSH’s preview to close it
5. Launch it again

After that, the following message dialog will be shown every time it’s launched, and it will be closed if I press the “goodbye” button.

![GitHawk Upload by kkk669](https://i.imgur.com/nTYTGXD.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ELChris414** [comment] 2018-11-21 17:17
I am trying to reproduce it, when you install fish do you get a post install error with a status code of 127?

**Comment by Mnpn03** [comment] 2018-11-21 17:21
Interesting. zsh doesn't work either, #103, but I'm not sure if it gives the same response as this. Is there any possibility you could take a look at the files in the Files app, perhaps that could tell us something, and maybe you can even revert it?

**Comment by ELChris414** [comment] 2018-11-21 17:34
Interesting, my iSH hangs and I cannot get it to not hang, dunno if I need to leave it some time, I am not very patient :P
Closing iSH and reopening it while it is hanged it keeps working just like normal.

**Comment by Mnpn03** [comment] 2018-11-21 17:35
I cannot replicate this on the master branch. It installs without any problems. Although it does still not run, it does not seem to spectacularly fail. `fish` freezes iSH, and I have to restart the app to get back. I can however replicate the 127 error on the TestFlight build, but restarting the app seems to be okay there too.

**Comment by kkk669** [comment] 2018-11-21 17:46
It could no longer replicate the issue after I reinstall the app again. Both versions are the same. Possibly, there is other conditions to replicate this. I’m sorry and thank you @ELChris414 and @Mnpn03.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mnpn03** [comment] 2018-11-21 17:47
No need to be sorry, as it is fully possible it was some database issue, quoting @tbodt regarding another problem:
```
probably some database inconsistency
the system killed the app before it was able to save some important file metadata
```

**Comment by ELChris414** [comment] 2018-11-21 18:13
Yeah man no worries. Just like Mnpn said most likely this is a database failure. Since this is a common issue and zsh instead of fish already has it's own issue, maybe close this one? The real issue apart from the database failure is the compatibility with fish.

**Comment by Mnpn03** [comment] 2018-11-21 18:14
No, I do believe you should keep the issue open until fish is working.

**Comment by ELChris414** [comment] 2018-11-21 18:15
Maybe then rename the issue to the appropriate thing, just to keep it organized

**Comment by Mnpn03** [comment] 2018-11-21 18:20
Looks fine to me, as the other problem is still (potentially, in certain cases) an issue. While they are separate issues this is not the first time iSH has failed like this, but this is "new". There was another case where folders turned to files, which rendered the app inoperable. I say you keep the title so that this issue could be more easily referenced in the case where this becomes a standalone issue, which will have to happen eventually.

**Comment by tbodt** [comment] 2018-11-21 21:05
I really need a better database, but there's another issue for that: #97. I also think a new issue should be created for fish.

**Closed by tbodt** 2018-11-21 21:05 UTC

**Comment by ELChris414** [comment] 2018-11-21 21:18
Done #122
