### ISSUE TITLE
passwd: can't lock /etc/[shadow/passwd]: invalid argument

### ISSUE THREAD

**Issue by BrychanOdlum** [tbodt/ish#285] opened 2019-01-23 17:41 UTC
When running `passwd` I have been getting the following warnings:

```
New password:
Retype password:
passwd: warning: can't lock '/etc/shadow': Invalid argument
passwd: warning: can't lock '/etc/passwd': Invalid argument
passwd: password for root changed by root
```

**Comment by BrychanOdlum** [comment] 2019-01-23 17:42
Following this, `login root` works with the new password, however I'm unable to login via ssh. This could be a separate issue.

**Comment by tbodt** [comment] 2019-01-23 19:13
Then invalid argument thing is a duplicate of #217. The ssh problem is because you need to enable AllowRootLogin in the ssh config file, which I forgot to mention in the update release notes.

**Closed by tbodt** 2019-01-23 19:13 UTC
