### ISSUE TITLE
terraform doesn’t work

### ISSUE THREAD

**Issue by samsonjs** [tbodt/ish#176] opened 2018-12-10 02:26 UTC
Attempting to run [terraform][] results in the error message `This program can only be run on processors with MMX support.`. It’s written in Go so maybe this is something specific to Go? Pure speculation.

[terraform]: https://www.terraform.io/

Happy to try to help if you can point me at something to get started. Not my area of expertise but I like this sort of stuff.

**Comment by tbodt** [comment] 2018-12-10 02:39
go programs require the MMX instruction set, and MMX is not implemented.

**Comment by tbodt** [comment] 2018-12-31 05:21
Closing as duplicate of #57

**Closed by tbodt** 2018-12-31 05:21 UTC
