### ISSUE TITLE
Slow startup time in ipython identified.

### ISSUE THREAD

**Issue by cwwalter** [tbodt/ish#602] opened 2020-01-01 04:02 UTC
When trying to start ipython (installed with apk) I was seeing about a full 2 minutes startup time.  This seemed out of line with the start up time of other programs .  By using control-c and looking at the stack trace I isolated the region to this code fragment in 

/usr/lib/python3.7/site-packages/IPython/core/completer.py

```
names = []		
 for c in range(0,0x10FFFF + 1):		
     try:		
         names.append(unicodedata.name(chr(c)))		
     except ValueError:		
         pass
```

Interestingly, I found that in the next release after the one included in alpine 3.10 this was moved to increase startup speed.

https://github.com/ipython/ipython/pull/11693

I updated my repository file to alpine 3.11 which got me ipython 7.10 after this PR was merged.  In this case the startup time is indeed more reasonable.  It should be noted that the issue is just moved. You can now trigger it by trying to do a tab-completion.

By running this code snippet separately (I did it in ipython itself for easy timing), on my 9.5" iPad pro I see a 1min 50 second run time. About 21 seconds of this is the loop over the million items itself, the rest the contents.  As a comparison the entire snippet takes about 680ms on my MacBook Pro.

I'm not sure if this is just to be expected in the emulator, but I thought it might be useful for you to have this very simple standalone test case.

**Comment by tbodt** [comment] 2020-01-01 05:39
Interesting. 70 seconds vs 0.68 seconds is a ~150x slowdown, which is not out of the ordinary for emulator slowdown. It might be worth digging a little more, but gonna call this a duplicate of #129.

**Closed by tbodt** 2020-01-01 05:39 UTC
