### ISSUE TITLE
ash or bash sleep not longer working 

### ISSUE THREAD

**Issue by francoisvignon** [tbodt/ish#321] opened 2019-02-20 08:51 UTC
at least with testflight 48, try
`sleep 2`
this one will never exit
but the following code (compiled in iSh with gcc, quick code, don't blame me):
```
main()                                           
{ sleep(2); }  
```
work fine.
busybox issue ?

**Comment by saagarjha** [comment] 2019-02-20 09:32
Hmm, this works fine for me on build 48?

**Comment by francoisvignon** [comment] 2019-02-20 09:39
I do a clean install (deleting iSH and then reinstallating from testflight, without any addition).
Installing from test fligh 1.0 (48), expiring in 82 days (today is 20/02/2019):
                                                 
```
You can install packages with: apk add <package> 
                                                 
You may change this message by editing /etc/motd.
                                                 
iFv:~# uname -a                                  
Linux iFv 3.2.0-ish SUPER AWESOME compiled on Feb
 11 2019 i686 Linux                              
iFv:~# sleep 2                                   
            

```
never exit ... (iOS 12.1.4, iPhone X)

**Comment by saagarjha** [comment] 2019-02-21 11:16
Can reproduce, seems to be some sort of sign conversion error in busybox. Once I can get iSH to clone and build busybox I'll take a look at what's going on here.

**Comment by francoisvignon** [comment] 2019-02-23 15:45
some informations:
I have tested ish (on Mac, under OSx, build from commit 3ce1aef):
first try with alpine 3.9.0 (BusyBox v1.29.3):
```
mcfv-1:~# date ; sleep 2 ; date
Sat Feb 23 15:37:35 UTC 2019
^C
mcfv-1:~# date
Sat Feb 23 15:37:55 UTC 2019
mcfv-1:~# busybox
BusyBox v1.29.3 (2019-01-24 07:45:08 UTC) multi-call binary.
```
the sleep never end and ^C should be issue to exit, shortly after ^C, I have show the date

then the same ish build with alpine 3.8.2 (busybox v1.28.4):
```
mcfv-1:~# date ; sleep 2 ; date
Sat Feb 23 15:37:03 UTC 2019
Sat Feb 23 15:37:05 UTC 2019
mcfv-1:~# busybox
BusyBox v1.28.4 (2018-12-06 15:13:21 UTC) multi-call binary.
```
all work fine.

so, the problem seem not be directly related to ish ...

**Comment by jonathan-w-king** [comment] 2019-03-06 04:57
Yup; I didn’t get this before I forced alpine 3.9.0 and got busybox 1.29.3, and now it hangs on any legal/reasonable argument to sleep. (So `sleep -1` complains, `sleep 0` returns immediately as does [e.g.] `sleep 0.5` and sleep [integer >= 1] hangs.

**Comment by saagarjha** [comment] 2019-03-06 09:50
FWIW, `sleep $(((1<<32)-$seconds))` will do what you want, at least until this issue is fixed.

**Comment by francoisvignon** [comment] 2019-03-06 10:06
Nice ;-)
thanks, will do a ´sleep' script according your note.


send from my mobile.
____________________

François

**Comment by tbodt** [comment] 2019-03-06 17:11
@saagarjha **wat**

**Comment by saagarjha** [comment] 2019-03-06 17:28
Yeah, that was pretty much my reaction as well; there's like two levels of conversions, and `sleep 1` ends up becoming 0xffffffff in iSH's `sys_nanosleep`. I was trying to figure out the stack a while back to see where this was coming from, but I didn't get too far…

**Comment by tbodt** [comment] 2019-03-09 23:25
```
                    case 0xd940: TRACE("fchs"); FCHS(); break;
                    case 0xd941: TRACE("fabs"); FABS(); break;
                    case 0xd944: TRACE("fchs"); FCHS(); break;
```

**Comment by tbodt** [comment] 2019-03-09 23:32
Fixed in efb9ed477bbd7797d16213eb7a604bfc38b93148

**Closed by tbodt** 2019-03-09 23:32 UTC
Labels: regression

**Comment by francoisvignon** [comment] 2019-03-09 23:36
nice ...  :-)

**Comment by saagarjha** [comment] 2019-03-09 23:40
As an aside, isn’t `ftst` 0xd9*e*4?

**Comment by tbodt** [comment] 2019-03-09 23:42
@saagarjha https://github.com/tbodt/ish/blob/efb9ed477bbd7797d16213eb7a604bfc38b93148/emu/decode.h#L651
