### ISSUE TITLE
Feature Request: Copy to and paste from clipboard

### ISSUE THREAD

**Issue by kkk669** [tbodt/ish#25] opened 2018-11-03 14:50 UTC
Currently, it is possible to copy selected text to a clipboard by tapping “Copy” on the context menu, but it seems that it is impossible to paste from it on iSH.

![bd0bd83f-a3d0-4927-aef5-36ce444fccad](https://user-images.githubusercontent.com/601636/47953590-19d7f400-dfc3-11e8-8bf6-b8d6c9cf26ef.png)

I believe both of them are essential. Besides, keyboard shortcuts like CMD+V are also welcome if possible.

- [x] Custom popup menu
- [x] Paste button in toolbar
- [x] Hardware keyboard shortcut

**Comment by tbodt** [comment] 2018-11-03 16:41
Pasting is indeed impossible, mostly because I'm not sure what the best UI would be for it. Long press maybe? Or a button in the toolbar?

**Comment by kkk669** [comment] 2018-11-03 17:04
I prefer a button in inputAccessoryView or the standard keyboard’s paste button like the following image.

![0c0eeeb8-a7dc-491b-bd10-0757ca5c4cb4](https://user-images.githubusercontent.com/601636/47955039-780dd280-dfd5-11e8-8dba-4591fa22aaed.jpeg)

In the other hand, for instance, [Blink](https://github.com/blinksh/blink) has a “Paste” item in the context menu. It’s a little bit weird, but it works.

![7db925c1-ea84-4206-bbdd-18196a78971f](https://user-images.githubusercontent.com/601636/47954968-77c10780-dfd4-11e8-88c4-0433262da9c8.jpeg)

**Comment by tbodt** [comment] 2018-11-03 18:05
Looking at the blink source code, a custom popup menu doesn't seem too hard. I've added a task list to the issue.

**Comment by tbodt** [comment] 2018-11-18 02:18
I got the context menu working.

**Comment by tbodt** [comment] 2018-11-28 04:45
Hardware keyboard shortcut apparently comes for free with context menu support.

**Comment by BoxOfSnoo** [comment] 2018-12-01 03:03
Context menu is great, though very difficult to bring up without a keyboard.  I agree with what @kkk669 requested, if possible.

**Comment by tbodt** [comment] 2018-12-03 20:55
I guess because WebKit is no longer the first responder. I'll have to implement `-copy` myself, which shouldn't be hard.

**Comment by kkk669** [comment] 2018-12-09 11:39
In the latest TestFlight build 35, when I just long press text to select it on iSH, it will be copied into the pasteboard even if I don’t tap the “Copy” item. Is this a bug?

I’m using 3rd generation 12.9” iPad Pro with iOS 12.1.1.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ELChris414** [comment] 2018-12-09 11:40
@kkk669 I cannot reproduce it.. I am iOS 12.1 tho, it might be a small bug with iOS 12.1.1

**Comment by kkk669** [comment] 2018-12-09 11:48
@ELChris414 I also reproduced on iPad Air 2 w/ **iOS 12.1** and iPhone XS with iOS 12.1.1. So, it’s not iOS 12.1.1 bug.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kkk669** [comment] 2018-12-09 11:54
How to reproduce it: https://youtu.be/OoDOArAkhSg

1. Select text
2. Tap “Paste” item

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ELChris414** [comment] 2018-12-09 11:56
Saw the video, still cannot reproduce. This is weird. It just keeps pasting my last copied, it does not renew the copy

**Comment by Mnpn03** [comment] 2018-12-09 15:03
I can replicate this on iOS 12.1.1. Please, create a new issue for this. Thanks

**Comment by tbodt** [comment] 2018-12-28 23:45
There's now a paste button on the toolbar, so I'll close this.

**Closed by tbodt** 2018-12-28 23:45 UTC

**Comment by 62f** [comment] 2020-09-15 04:02
Now that iOS 13.7 has introduced a copy/paste dialog within the touch-keyboardless full screen view of the scrollback, I totally forgot about iSH’s button and was absentmindedly trying to paste by using the floating dialog. It is possible, but very tricky; the kb has to stay hidden, which it thoroughly dislikes.
