### ISSUE TITLE
Can’t install python pandas package with pip3

### ISSUE THREAD

**Issue by sausheong** [tbodt/ish#177] opened 2018-12-10 06:15 UTC
Can’t install python pandas package using pip3. 

![img_0056](https://user-images.githubusercontent.com/5962/49713975-0127c180-fc86-11e8-83e3-59e5390e3610.png)

**Comment by tbodt** [comment] 2018-12-10 06:16
Duplicate of #126

**Comment by tbodt** [comment] 2018-12-10 06:16
You can install working numpy binaries using apk.

**Closed by tbodt** 2018-12-10 06:16 UTC

**Comment by ifuchs** [comment] 2021-05-22 21:24
Has anyone gotten any further with installing pandas?
