### ISSUE TITLE
Add Apple Files app bookmark support

### ISSUE THREAD

**Issue by mwiget** [tbodt/ish#586] opened 2019-12-16 06:29 UTC
I'm using iSH successfully to manage files with git and use [MWeb](https://www.mweb.im/) to edit markdown files. This works ok by opening Apple's Files app, select iSH, find the file markdown in the iSH root file system and click it. This opens MWeb and I can edit the file there and it is saved as well back into iSH successfully.

![IMG_0507](https://user-images.githubusercontent.com/3111088/70884195-923a2280-1fd5-11ea-8e1b-fe0f6bcc8502.jpeg)

Now it would be ideal to be able to bookmark the directory in MWeb, so I can access my isH folder directly from there. According to the MWeb developers, this requires iSH to have better Files support.

**Comment by tbodt** [comment] 2019-12-16 06:43
I believe this is a dupe of #496. Please let me know if it isn't.

**Closed by tbodt** 2019-12-16 06:43 UTC
