### ISSUE TITLE
Installing Miniconda errors out

### ISSUE THREAD

**Issue by dopplershift** [tbodt/ish#555] opened 2019-11-07 22:55 UTC
I’d love to be able to do a custom Python installation on ish, using a Linux build of Miniconda. Unfortunately, that errors out:

```
Ryans-iPad:~# chmod +x Miniconda3-latest-Linux-x86.sh 
Ryans-iPad:~# ./Miniconda3-latest-Linux-x86.sh -b
PREFIX=/root/miniconda3
installing: python-3.7.1-h0371630_7 ...
./Miniconda3-latest-Linux-x86.sh: line 385: /root/miniconda3/pkgs/python-3.7.1-h0371630_7/bin/python: not found
```
I can confirm that the python binary is in that location, but trying to directly execute it just says “not found”. Happy to do more debugging if someone can point me in a direction.

**Comment by tbodt** [comment] 2019-11-08 03:10
Duplicate of #355

**Closed by tbodt** 2019-11-08 03:10 UTC
