### ISSUE TITLE
Add MMX processor support

### ISSUE THREAD

**Issue by MFDGaming** [tbodt/ish#477] opened 2019-09-09 13:00 UTC
When I run ngrok I get this message:

This program can only be run on processors with MMX support.

**Comment by MFDGaming** [comment] 2019-09-09 13:01
![20953761-74DB-4402-BB51-9CB3037717D1](https://user-images.githubusercontent.com/38327951/64532911-187e0300-d31b-11e9-8f49-07169ea39c2f.png)

**Comment by Rexogamer** [comment] 2019-09-09 15:36
Wouldn’t this be a system thing? Unless iSH can emulate processors...

**Comment by itskenny0** [comment] 2019-09-09 16:01
This is a duplicate of #57.

@Rexogamer iSH _is_ emulating a CPU. The binaries are x86.

**Closed** 2019-09-09 16:29 UTC
