### ISSUE TITLE
Pip fails to build cffi - illegal instructions

### ISSUE THREAD

**Issue by yaakov-h** [tbodt/ish#155] opened 2018-12-03 03:40 UTC
Next failure along the path to #152.

Illegal instruction in GCC when running `pip install cffi`.

![img_0074](https://user-images.githubusercontent.com/426009/49351788-2443f580-f709-11e8-92bb-e4d13dfb4bff.png)

**Comment by tbodt** [comment] 2018-12-03 05:13
Seems like a duplicate of #126

**Closed by tbodt** 2018-12-03 05:13 UTC
