### ISSUE TITLE
Keybase does not install

### ISSUE THREAD

**Issue by b-** [tbodt/ish#618] opened 2020-01-17 15:58 UTC
Upon installing golang (`apk add go`) I attempted to `go get keybase/client`

Expected result: Keybase should compile and install. 

Actual result: “This program can only be run on processors with MMX support.”

I thought the emulated CPU was a Pentium with MMX?

**Comment by tbodt** [comment] 2020-01-17 17:35
It's more of a i486. No MMX support.

Duplicate of #57

**Closed by tbodt** 2020-01-17 17:35 UTC
