### ISSUE TITLE
Feature Request: Open iOS URLs

### ISSUE THREAD

**Issue by jacobshapiro** [tbodt/ish#568] opened 2019-11-22 05:30 UTC
It would be nice if iSH handled the 'open' command via iOS. E.g., executing "open http://google.com" would trigger an iOS event of having clicked such a URL. This could work with other apps too that register URL handlers and allow better integration with iOS. For example, it could tell a PDF viewer to update the view (and even to set a certain page) after a re-generation of a document.

**Comment by tbodt** [comment] 2019-11-22 05:32
Duplicate of #471

**Closed by tbodt** 2019-11-22 05:32 UTC
