### ISSUE TITLE
Feature request: support location tracking to eliminate the background limit

### ISSUE THREAD

**Issue by m4rkw** [tbodt/ish#513] opened 2019-10-11 19:42 UTC
iOS 13 reduced the maximum background runtime from 3mins to 30 seconds *except* for apps that track location.

I would like a location-tracking option that when enabled allows you to set the maximum background runtime in minutes all the way up to "forever". This would be awesome for developers who want to run a local web dev stack and access it via safari or other tools.

**Comment by Rexogamer** [comment] 2019-10-11 19:43
iOS 30?

**Comment by m4rkw** [comment] 2019-10-11 19:44
Oops, fixed.

**Comment by Regularcheckm8** [comment] 2019-10-12 00:24
Doesn't Location services require things to have to have them to run in the background? for example to run google maps transit in the background you have to have a set destination and it has to be planning a route, checking traffic and updating your location not anything else. The only way to run commands in the background is to have location services enabled at all times and if not the command won't work, right? Please correct me if I'm wrong (might be useful for the future)

**Comment by m4rkw** [comment] 2019-10-12 07:06
I don't know but Shelly has this feature and that's an SSH client. If you enable location tracking it can keep connections alive in the background indefinitely.

**Comment by tbodt** [comment] 2019-10-12 17:34
This is really a duplicate of #249, but location tracking is possibly a good idea. Background audio probably uses less battery though.

**Closed by tbodt** 2019-10-12 17:34 UTC
