### ISSUE TITLE
Cannot install Azure CLI (Python)

### ISSUE THREAD

**Issue by yaakov-h** [tbodt/ish#152] opened 2018-12-02 01:17 UTC
I'm trying to install the Azure CLI and after much back-and-forth I think I'm close, but still not close enough.

1. `apk add curl gcc python musl-dev  libffi bash libffi-dev python-dev`
1. `curl -L https://azurecliprod.blob.core.windows.net/install.py > install.py`
1. `python install.py`
1. Press enter
1. Press enter again
1. Wait (a rather long time) for Python packages to download and install
1. Observe that pip crashed with a MemoryError

At this point I can't even run `install.py` again without getting another MemoryError (until force-quitting and restarting iSH resets the memory issue)

I'm trying this on an iPad Pro (MU102X/A) on iOS 12.1 (16B92).

**Comment by tbodt** [comment] 2018-12-02 01:18
I just fixed a pretty bad memory leak that was making pip often throw a MemoryError. Can you try building the app from source and seeing if that works better?

**Comment by yaakov-h** [comment] 2018-12-02 01:49
I'll give that a shot a bit later and see how it goes.

**Comment by ChrisPatten** [comment] 2018-12-03 13:57
I’m not seeing any out of memory since the last release, but I’m getting an illegal instruction error. 
![46f79c5f-2eab-41a5-8191-a0ac4b82c264](https://user-images.githubusercontent.com/1243070/49377932-66edd980-f6d9-11e8-8410-26933600ed80.jpeg)

**Comment by tbodt** [comment] 2018-12-03 16:49
That was reported as #155, it's a duplicate of #126

**Comment by tbodt** [comment] 2018-12-09 02:17
Closing as duplicate of #126

**Closed by tbodt** 2018-12-09 02:17 UTC
