### ISSUE TITLE
Web Assembly for increased performance.

### ISSUE THREAD

**Issue by jcampbell05** [tbodt/ish#610] opened 2020-01-07 12:30 UTC
I am interested if performance could be enhanced by using Web Assembly, here is my concept:

- Gadgets rewritten in Web Assembly Intermediate Format which is compiled into WASM.
- Or main interpretation code is compiled into WASM directly.

Once compiled all emulation code is ran using WASM code inside of a hidden WKWebView which allows for iOS's native JIT to execute the code- potentially this gives us near native speeds.

Input and graphics can be passed to/from the native UIView via some sort of web socket - creating a local VNC.

I am willing to test this out but was wondering where to being.

**Comment by tbodt** [comment] 2020-01-07 16:16
I've written a bit about this here: https://github.com/tbodt/ish/issues/102#issuecomment-439561835

Closing as duplicate of #129. We can discuss further there.

**Closed by tbodt** 2020-01-07 16:16 UTC
